[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
bytecode_hash = "none"
cbor_metadata = false
optimize = true
via-ir = true
runs = 1000

[profile.deploy]
via-ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[fuzz]
runs = 256

[dependencies]
eth-infinitism-account-abstraction = "0.8.0"
solady = "0.1.26"
