[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
via_ir = true
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 20_000


[dependencies]
eth-infinitism-account-abstraction = "0.8.0"
solady = "0.1.26"
forge-std = "1.11.0"
"@openzeppelin-contracts" = "5.5.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
